version: '3.8'
services:
  langchain-academy:
    container_name: langchain_academy
    build: .
    volumes:
      - ./:/home/app
    ports:
      - "8778:8778"
    environment:
      - PYTHONUNBUFFERED=1
